### ISSUE TITLE
Segmentation violation with htcat

### ISSUE THREAD

**Issue by ErikKassubek** [ErikKassubek/dedego#21]
DedegoRecv: C,1,R,o,1,/home/erikkassubek/Uni/dedego/go-patch/src/runtime/mgc.go:180
DedegoRecv: C,1,R,o,2,/home/erikkassubek/Uni/dedego/go-patch/src/runtime/mgc.go:181
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x407ece]

goroutine 1 [running]:
net/http.(*Transport).roundTrip(0x873f40, 0xc00015e100)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/transport.go:573 +0x607
net/http.(*Transport).RoundTrip(0x59d?, 0x6f6040?)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/roundtrip.go:17 +0x13
net/http.send(0xc00015e000, {0x6f6040, 0x873f40}, {0xc000069a01?, 0x456dc9?, 0x0?})
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:260 +0x606
net/http.(*Client).send(0xc0001269c0, 0xc00015e000, {0x42b1db?, 0xc000069a58?, 0x0?})
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:181 +0x98
net/http.(*Client).do(0xc0001269c0, 0xc00015e000)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:724 +0x912
net/http.(*Client).Do(...)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:590
main.(*HtCat).startup(0xc00012a960, 0x5)
	/home/erikkassubek/Uni/dedego/examples/htcat/http.go:50 +0x125
main.New(0xc0001269c0, 0xc00015c000, 0x5)
	/home/erikkassubek/Uni/dedego/examples/htcat/http.go:154 +0x1e6
main.main()
	/home/erikkassubek/Uni/dedego/examples/htcat/htcat.go:98 +0x246

**Comment by ErikKassubek** [comment]
Same with gocrawl

[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x407f8e]

goroutine 6 [running]:
net/http.(*Transport).roundTrip(0x91dc40, 0xc000138000)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/transport.go:573 +0x607
net/http.(*Transport).RoundTrip(0x89b568?, 0x756c00?)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/roundtrip.go:17 +0x13
net/http.send(0xc000138000, {0x756c00, 0x91dc40}, {0x954001?, 0xffffff?, 0x0?})
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:260 +0x606
net/http.(*Client).send(0x919000, 0xc000138000, {0x41a0c8?, 0x424e7c?, 0x0?})
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:181 +0x98
net/http.(*Client).do(0x919000, 0xc000138000)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:724 +0x912
net/http.(*Client).Do(...)
	/home/erikkassubek/Uni/dedego/go-patch/src/net/http/client.go:590
main.(*DefaultExtender).Fetch(0xc000112070?, 0x0?, {0x6eff54, 0x3a}, 0xef?)
	/home/erikkassubek/Uni/dedego/examples/gocrawl/ext.go:155 +0x15f
main.(*worker).fetchURL(0xc0000f9ea0, 0xc00002f080, {0x6eff54, 0x3a}, 0x20?)
	/home/erikkassubek/Uni/dedego/examples/gocrawl/worker.go:226 +0x123
main.(*worker).requestRobotsTxt(0xc0000f9ea0, 0x6dd1b2?)
	/home/erikkassubek/Uni/dedego/examples/gocrawl/worker.go:152 +0x75
main.(*worker).run(0xc0000f9ea0)
	/home/erikkassubek/Uni/dedego/examples/gocrawl/worker.go:84 +0x308
created by main.(*Crawler).launchWorker in goroutine 1
	/home/erikkassubek/Uni/dedego/examples/gocrawl/crawler.go:177 +0x216

**Comment by ErikKassubek** [comment]
Both caused by /src/net/http/transport.go:573

```go
select {
case <-ctx.Done():  // this line causes seg fault
    req.closeBody()
    return nil, ctx.Err()
default:
}
```
